#!/bin/bash

add_init_file=true             # -i
used_version="2011-10-01"      # -v
just_test=                     # -T

quicklisp_lisp="quicklisp.lisp"
quicklisp_url="http://beta.quicklisp.org/$quicklisp_lisp"

install_quicklisp=install_quicklisp.lisp
sharedir=share

for arg in "$@"
do
  case "$arg" in
    -i*)
      add_init_file=${arg:2}
      ;;

    -v*)
      used_version=${arg:2}
      ;;

    -T*)
        just_test=true
      ;;

  esac

done

echo "Remote file: $quicklisp_url"
echo "

(load \"quicklisp.lisp\")
(quicklisp-quickstart:install)
(let ((version_url (cdr (assoc \"$used_version\" (ql-dist:available-versions (ql-dist:dist \"quicklisp\")) :test #'string=))))
  (ql-dist:install-dist version_url :replace t))

" > $install_quicklisp

if [[ $add_init_file = "true" ]]
then
    echo "
(ql:add-to-init-file)
    ">> $install_quicklisp
fi
echo "(quit)">> $install_quicklisp
echo "quicklisp install script generated at $install_quicklisp"


if [[ $just_test = "" ]]
then
    rootdir=`pwd`
    cd $sharedir
    if [[ -f $quicklisp_lisp ]]
    then
        echo "Use $sharedir/$quicklisp_lisp to install"
    else
        echo "Fetching $quicklisp_url ..."
        wget $quicklisp_url
    fi

    sbcl --load $install_quicklisp
    cd $rootdir
fi

